# fly.toml app configuration file generated for extension-server on 2023-06-04T15:06:28+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shandurpy-server"
primary_region = "dfw"

[build]
  dockerfile = "./server.Dockerfile"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

[env]
  HOST="https://shandurpy-server.fly.dev"
  PORT="3001"


